#------------------------------------------------------------------------------#
# Wave propagation 
#
# Makefile ./tests/03
#------------------------------------------------------------------------------#

default:

install:

# Cleaning
#------------------------------------------------------------------------------#

.PHONY: clean
clean:
	-@ rm -vf *~ .*.sw? sf*
	-@ rm -vf output.dat
	-@ rm -vf ./specs/*
	-@ rm -vf ./velocity/*
	-@ rm -vf ./snaps/*
	-@ rm -vf ./traces/*

.PHONY: distclean
distclean: clean
	-@ rm -rvf ./specs
	-@ rm -rvf ./velocity
	-@ rm -rvf ./snaps
	-@ rm -rvf ./traces

#------------------------------------------------------------------------------#
